### GET ALL
GET http://localhost:3000/api/pacientes

### POST
# @name createPaciente
Post http://localhost:3000/api/pacientes

### POST PACIENTE TO DELETE
# @name createPacienteToDelete
POST http://localhost:3000/api/pacientes

###
@id = {{createPaciente.response.body.data.id}}

### Get one
Get  http://localhost:3000/api/pacientes/{{id}}

### DELETE
@idToDelete = {{createPacienteToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/pacientes/{{idToDelete}}